# .github/workflows/deploy-prod.yml
name: Deploy Lambda

on:
  push:
    branches: [master, dev]

env:
  stage: ${{ fromJSON('{"master":"prod","dev":"dev"}')[github.ref] }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'master' && 'prod' || 'dev' }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Echo ref
        run: echo ${{ github.ref }}
      - name: Echo var stage
        run: echo ${{ vars.STAGE }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - name: Serverless Deploy
        uses: serverless/github-action@v3.1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy --stage ${{ vars.STAGE }}