# .github/workflows/deploy.yml
name: Sync Dev

on:
  push:
    branches: [master]

env:
  deploy_stage: ${{ vars.STAGE }}

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: echo "Env var STAGE - $deploy_stage" 

      - name: Serverless Deploy
        uses: serverless/github-action@v3.1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy --stage $deploy_stage